
---
title: "PRODUCT DESIGN"
date: 2019-03-28
---

title: HOW TO DESIGN A PRODUCT
author: Gaurav Chauhan
email: gauravchauhan3991@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first blog.Here i am discussing about how to design a product.

# social links
github_username:  Gauravchauhan0120

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
